name: stagess_common
description: A sample command-line application.
version: 1.1.10
# repository: https://github.com/my_org/my_repo
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  enhanced_containers_foundation:
  collection: ^1.16.0
  http: ^1.3.0
  latlong2: ^0.10.1
  routing_client_dart: ^1.0.7
  uuid: ^4.5.1
  image: ^4.5.4
  xml: ^7.0.1
  meta: ^1.17.0

dependency_overrides:
  enhanced_containers_foundation:
    path: ../external/enhanced_containers/plugins/enhanced_containers_foundation

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
